name: community_safety
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: InstrumentSans
      fonts:
        - asset: fonts/InstrumentSans-Bold.ttf
          weight: 700
        - asset: fonts/InstrumentSans-Medium.ttf
          weight: 500
        - asset: fonts/InstrumentSans-Regular.ttf
          weight: 400
        - asset: fonts/InstrumentSans-SemiBold.ttf
          weight: 600